### ISSUE TITLE
Error while reading groups with non-ascii symbols

### ISSUE THREAD

**Issue by pokidovea** [pschmitt/pykeepass#20]
I have a db with groups in russian. When I'm trying to show entries I have this
```
>>> kp.entries
[Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-15: ordinal not in range(128)
```
Under python 3.5 works fine, but under python 2.7 - not.

**Comment by pschmitt** [comment]
Would you mind providing the database file you used? Or maybe a dummy one with at least one special character in it so that I can reproduce the problem your are describing?

**Comment by pokidovea** [comment]
Sure,
[test.kdbx.zip](https://github.com/pschmitt/pykeepass/files/995322/test.kdbx.zip)
```
>>> from pykeepass import PyKeePass
>>> kp = PyKeePass('test.kdbx', password='123')
>>> kp.entries
[Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-13: ordinal not in range(128)
>>> kp.groups
[Group: "/", Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-13: ordinal not in range(128)
```
