### ISSUE TITLE
Unknown header field on kdbx4 database

### ISSUE THREAD

**Issue by jleclanche** [pschmitt/pykeepass#80]
```pytb
Traceback (most recent call last):
  File "import_kdbx.py", line 32, in <module>
    main()
  File "import_kdbx.py", line 28, in main
    rows += parse_kdbx(filename, password)
  File "import_kdbx.py", line 8, in parse_kdbx
    kp = PyKeePass(filename, password=password)
  File "/home/adys/.local/share/virtualenvs/tmp-842ade25992ba7a/lib/python3.6/site-packages/pykeepass/pykeepass.py", line 25, in __init__
    self.kdb = self.read(filename, password, keyfile)
  File "/home/adys/.local/share/virtualenvs/tmp-842ade25992ba7a/lib/python3.6/site-packages/pykeepass/pykeepass.py", line 38, in read
    filename, **credentials
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/adys/.local/share/virtualenvs/tmp-842ade25992ba7a/lib/python3.6/site-packages/libkeepass/__init__.py", line 42, in open
    kdb = cls(stream, **credentials)
  File "/home/adys/.local/share/virtualenvs/tmp-842ade25992ba7a/lib/python3.6/site-packages/libkeepass/kdb4.py", line 417, in __init__
    KDB4File.__init__(self, stream, **credentials)
  File "/home/adys/.local/share/virtualenvs/tmp-842ade25992ba7a/lib/python3.6/site-packages/libkeepass/kdb4.py", line 64, in __init__
    KDBFile.__init__(self, stream, **credentials)
  File "/home/adys/.local/share/virtualenvs/tmp-842ade25992ba7a/lib/python3.6/site-packages/libkeepass/common.py", line 149, in __init__
    self.read_from(stream, unprotect)
  File "/home/adys/.local/share/virtualenvs/tmp-842ade25992ba7a/lib/python3.6/site-packages/libkeepass/kdb4.py", line 420, in read_from
    KDB4File.read_from(self, stream)
  File "/home/adys/.local/share/virtualenvs/tmp-842ade25992ba7a/lib/python3.6/site-packages/libkeepass/kdb4.py", line 82, in read_from
    super(KDB4File, self).read_from(stream)
  File "/home/adys/.local/share/virtualenvs/tmp-842ade25992ba7a/lib/python3.6/site-packages/libkeepass/common.py", line 161, in read_from
    self._read_header(stream)
  File "/home/adys/.local/share/virtualenvs/tmp-842ade25992ba7a/lib/python3.6/site-packages/libkeepass/kdb4.py", line 119, in _read_header
    raise IOError('Unknown header field found.')
OSError: Unknown header field found.
```

I printed the header field and field_id = `90`. Any idea?

**Comment by jleclanche** [comment]
Looks like libkeepass doesn't support Argon2

**Comment by Evidlo** [comment]
`libkeepass` only supports `kdb` and `kdbx v3`.  See https://github.com/libkeepass/libkeepass/issues/24

**Comment by jleclanche** [comment]
Why does it say "and KeePass 2.x (v4) files" then?

I worked around my issue by converting my 4.x db into a 3.1 one, but I guess I'll close in favor of that issue then.

**Comment by Evidlo** [comment]
https://github.com/libkeepass/libkeepass_proto/issues/1
